New features
timusus/RecyclerView-FastScroll pull request #73
Opened 2018-02-05 16:06 UTC by jahirfiquitiva

- Allow showing scrollbar from FastScrollRecyclerView
- Rename `setThumbInactiveColor` method to `allowThumbInactiveColor` in order to make it more intuitive.
- Allow changing inactive thumb color
- Rename `setStateChangeListener` to `setOnScrollbarStateChangeListener` in order to make it more intuitive.
- Update attributes. Set allowThumbInactiveColor to true by default
- Update attribute in sample
- Pass the item ViewHolder to MeasurableAdapter to ease the item height calculation

2018-02-05 22:44 UTC, timusus reviewed
I'd prefer `setOnFastScrollStateChangeListener`, as we refer to it as `FastScroll` rather than `ScrollBar`. If you specifically mean the thumb, it should be `setOnFastScrollThumbStateChangeListener`.

2018-02-05 22:45 UTC, timusus reviewed
I'd rather use 'enable' than 'allow', just for convention.

`enableThumbInactiveColor(boolean enabled)`

2018-02-05 22:49 UTC, timusus commented
Thanks for these great contributions.

I've added a few comments, mostly just semantic things.  Could you also update the readme to reflect these changes?

2018-02-05 22:50 UTC, timusus requested changes
Just some minor semantics. Feel free to discuss, you're not obliged to make these changes if you disagree with them.

2018-02-06 00:03 UTC, jahirfiquitiva commented
@timusus 
I have added the requested changes. Regarding the README update, should I add a new version to the list mentioning these changes? ... Probably version `1.0.18` ?

2018-02-06 00:36 UTC, timusus commented
No that's ok, I'll do the versioning when I release it.

2018-02-11 04:20 UTC, timusus commented
@jahirfiquitiva I'll merge this in, just waiting for that readme update, if you don't mind.

2018-02-11 14:08 UTC, jahirfiquitiva commented
@timusus 
I just don't know what to change. There is nothing in the README mentioning the things that were changed

2018-02-12 00:18 UTC, timusus commented
OK, no worries. I had assumed there would be some references to the method names or attributes which have changed, but it looks like they're not referenced in the readme,

2018-05-03 00:12 UTC, timusus approved these changes

2018-05-03 00:46 UTC, merged